marvel:
    image: es_local
    command: "elasticsearch -Des.cluster.name=marvel_local -Des.node.name=marvel -Des.marvel.agent.enabled=false"
    ports:
      - "19200:9200"
      - "19300:9300"

elasticsearch_master:
    image: es_local
    command: "elasticsearch -Des.node.name=master -Des.cluster.name=elasticsearch_local -Des.node.master=true -Des.node.data=false -Des.marvel.agent.exporter.es.hosts=marvel"
    environment:
      - ES_HEAP_SIZE=512m
    links:
      - marvel
    ports:
      - "9200:9200"
      - "9300:9300"

elasticsearch_data_1:
    image: es_local
    command: "elasticsearch -Des.node.name=data1 -Des.cluster.name=elasticsearch_local -Des.node.master=false -Des.node.data=true -Des.discovery.zen.ping.unicast.hosts=elasticsearch_master -Des.marvel.agent.exporter.es.hosts=marvel"
    links:
      - elasticsearch_master
      - marvel
    volumes:
      - "/opt/elasticsearch/data"
    environment:
       - ES_HEAP_SIZE=512m

elasticsearch_data_2:
    image: es_local
    command: "elasticsearch -Des.node.name=data2 -Des.cluster.name=elasticsearch_local -Des.node.master=false -Des.node.data=true -Des.discovery.zen.ping.unicast.hosts=elasticsearch_master -Des.marvel.agent.exporter.es.hosts=marvel"
    links:
      - elasticsearch_master
      - marvel
    volumes:
      - "/opt/elasticsearch/data"
    environment:
       - ES_HEAP_SIZE=512m

elasticsearch_agg_1:
    image: es_local
    command: "elasticsearch -Des.node.name=agg1 -Des.cluster.name=elasticsearch_local -Des.node.master=false -Des.node.data=false -Des.discovery.zen.ping.unicast.hosts=elasticsearch_master -Des.marvel.agent.exporter.es.hosts=marvel"
    links:
      - elasticsearch_master
      - marvel
    volumes:
      - "/opt/elasticsearch/data"
    environment:
       - ES_HEAP_SIZE=512m

elasticsearch_agg_2:
    image: es_local
    command: "elasticsearch -Des.node.name=agg2 -Des.cluster.name=elasticsearch_local -Des.node.master=false -Des.node.data=false -Des.discovery.zen.ping.unicast.hosts=elasticsearch_master -Des.marvel.agent.exporter.es.hosts=marvel"
    links:
      - elasticsearch_master
      - marvel
    volumes:
      - "/opt/elasticsearch/data"
    environment:
       - ES_HEAP_SIZE=512m
